Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.7/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
interval_sepal_length = cut("sepal.length", 3)
interval_petal_length = cut("petal.length", 3)
interval_sepal_width = cut("sepal.width", 3)
interval_petal_width = cut("petal.width", 3)

print("interval sepal.length = ", interval_sepal_length)
print("interval petal.length = ", interval_petal_length)
print("interval sepal.width = ", interval_sepal_width)
print("interval petal.width = ", interval_petal_width)
------------------

[0;31m[0m
[0;31mNameError[0mTraceback (most recent call last)
[0;32m<ipython-input-109-3137ac626cfc>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0minterval_sepal_length[0m [0;34m=[0m [0mcut[0m[0;34m([0m[0;34m"sepal.length"[0m[0;34m,[0m [0;36m3[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0minterval_petal_length[0m [0;34m=[0m [0mcut[0m[0;34m([0m[0;34m"petal.length"[0m[0;34m,[0m [0;36m3[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0minterval_sepal_width[0m [0;34m=[0m [0mcut[0m[0;34m([0m[0;34m"sepal.width"[0m[0;34m,[0m [0;36m3[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0minterval_petal_width[0m [0;34m=[0m [0mcut[0m[0;34m([0m[0;34m"petal.width"[0m[0;34m,[0m [0;36m3[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;32m<ipython-input-107-5aa277db10d1>[0m in [0;36mcut[0;34m(col, k)[0m
[1;32m      1[0m [0;32mdef[0m [0mcut[0m[0;34m([0m[0mcol[0m[0;34m,[0m [0mk[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m   [0mintervals[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mcut[0m[0;34m([0m[0mdata[0m[0;34m[[0m[0mcol[0m[0;34m][0m[0;34m,[0m [0mk[0m[0;34m)[0m[0;34m.[0m[0mvalue_counts[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mindex[0m[0;34m.[0m[0mto_list[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m   [0;32mreturn[0m [0;34m[[0m[0;34m[[0m[0minterval[0m[0;34m.[0m[0mleft[0m[0;34m,[0m [0minterval[0m[0;34m.[0m[0mright[0m[0;34m][0m [0;32mfor[0m [0minterval[0m [0;32min[0m [0mintervals[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'data' is not defined
NameError: name 'data' is not defined

